# Generated by Django 4.2.7 on 2023-12-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0002_tournee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('default', models.BooleanField(default=False)),
                ('est_modifie', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.client')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.tournee')),
            ],
        ),
    ]
