# Generated by Django 4.2.7 on 2023-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0003_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('taille', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True)),
                ('types', models.CharField(choices=[('C', 'Caisse'), ('U', 'Unite')], max_length=1)),
            ],
        ),
    ]
