# Generated by Django 4.2.7 on 2023-12-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id_caisse', models.AutoField(primary_key=True, serialize=False)),
                ('nbr_articles', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.article')),
            ],
        ),
    ]
