# Generated by Django 4.2.7 on 2023-12-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0005_caisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse_commande',
            fields=[
                ('id_caisse_commande', models.AutoField(primary_key=True, serialize=False)),
                ('nbr_caisse', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unite', models.IntegerField(default=0)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.caisse', unique=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.commande', unique=True)),
            ],
        ),
    ]
