# Generated by Django 4.2.7 on 2023-12-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
