# Generated by Django 4.2.7 on 2023-12-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0007_alter_commande_id_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='est_livre',
            field=models.BooleanField(default=False),
        ),
    ]
