# Generated by Django 4.2.7 on 2023-12-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0008_commande_est_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
