# Generated by Django 4.2.7 on 2023-12-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0008_commande_est_livre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse_commande',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.caisse'),
        ),
        migrations.AlterField(
            model_name='caisse_commande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.commande'),
        ),
    ]
