# Generated by Django 4.2.7 on 2023-12-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0009_alter_caisse_commande_caisse_and_more'),
        ('snappies', '0009_caisse_test'),
    ]

    operations = [
    ]
