# Generated by Django 4.2.7 on 2023-12-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0010_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
       
    ]
