# Generated by Django 4.2.7 on 2023-12-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0010_merge_20231210_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caisse_commande',
            old_name='nbr_caisse',
            new_name='nbr_caisses',
        ),
        migrations.AlterField(
            model_name='caisse_commande',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.caisse', unique=True),
        ),
        migrations.AlterField(
            model_name='caisse_commande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.commande', unique=True),
        ),
    ]
