# Generated by Django 4.2.7 on 2023-12-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('snappies', '0011_remove_user_user_permissions'),
    ]

    operations = [
       
    ]
