# Generated by Django 4.2.7 on 2023-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0012_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
       
    ]
