# Generated by Django 4.2.7 on 2023-12-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0013_remove_user_groups_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
