# Generated by Django 4.2.7 on 2023-12-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0016_alter_user_username'),
    ]

    operations = [
        
    ]
