# Generated by Django 4.2.7 on 2023-12-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0025_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
    ]
