# Generated by Django 4.2.7 on 2023-12-09 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappies', '0026_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id_tournee', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('isAdmin', models.BooleanField(default=False)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etapes_tournee',
            fields=[
                ('id_etape_tournee', models.AutoField(primary_key=True, serialize=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.commande')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snappies.tournee')),
            ],
        ),
    ]
