# test articles

### get all articles
GET http://localhost:8000/articles/get_all_clients_free
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


### Créer un artcile 
POST http://localhost:8000/articles/create_article
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

{
  "nom": "salut",
  "type": "C",
  "nbr_articles" : 12
}

### delete all articles
DELETE  http://localhost:8000/articles/delete_article/35
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


### Créer un artcile 
PATCH  http://localhost:8000/articles/update_article/6
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

{
  "nom": "sacs poubelles update",
  "nbr_articles": 200
}
 