
GET http://localhost:8000/articles/get_all_clients_free
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

### Créer un client 
POST http://localhost:8000/client/create_client
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

{
  "name": "client 3",
  "numero_telephone": "04214763333",  
  "adresse": "chausse d'anvers"
}

### delete client
DELETE http://localhost:8000/client/delete_client/2
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

### Mettre à jour un client
PUT http://localhost:8000/client/update_client/1
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

{
  "name": "nouveau nom",
  "numero_telephone": "9999999",  
  "adresse": "nouvelle adresse"
}


### get 
GET http://localhost:8000/client/get_all_clients_free
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


