


###
GET http://localhost:8000/commande/get_commandes_tournee_admin/1
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


###
GET http://localhost:8000/commande/get_commandes_tournee_modifie_ou_non/1
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


###Créer un utilisateur avec la méthode POST
POST http://localhost:8000/commande/create_commande
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

{
    "id_client": 8,
    "articles": [
        {
            "id_article": 1,
            "nbr_caisses": 3,
            "unite": 0
        },
        {
            "id_article": 4,
            "nbr_caisses": 3,
            "unite": 0
        },
        {
            "id_article": 5,
            "nbr_caisses": 0,
            "unite": 15
        }
    ],
    "id_tournee": 1
}

### udpate livraison
PATCH  http://localhost:8000/commande/update_livraison/59
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2



## token admin2 = 0aa1967b91c4c1232cf87c8c6373a035d08255d2
##47cf7bb92dbfa2649aa20fd3ff1fa82de9a94771

### Update commande by id 
PUT http://localhost:8000/commande/update_commande_admin/53
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

{
    "articles": [
        {
            "is_deleted": "false",
            "is_created": "false",
            "id_article": 1,
            "nbr_caisses": 12,
            "unite": 0
        },
        {
            "is_deleted": "false",
            "is_created": "false",
            "id_article": 4,
            "nbr_caisses": 10,
            "unite": 0
        }
      
    ]
}






###
GET http://localhost:8000/commande/getAll
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


###
GET http://localhost:8000/commande/getOne/1


### Marquer la commande 1 comme livré
PUT http://localhost:8000/commande/commande_livre/1
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

{}