

### login an user
POST http://localhost:8000/login/loginUser
Content-Type: application/json

{
    "username": "ronaldo",
    "password": "aze"
}



###
GET http://localhost:8000/login/getAllUsers

###
GET http://localhost:8000/login/getAllLivreurs
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


###
GET http://localhost:8000/login/get_users_connected


### Créer un utilisateur avec la méthode POST
POST http://localhost:8000/login/create
Content-Type: application/json

{
  "username": "livreur random",
  "password": "aze",  
  "is_admin": false
}

### delete user
DELETE http://localhost:8000/login/delete_livreur/18
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


###
PUT http://localhost:8000/login/update_user/1
Content-Type: application/json

{
  "new_username": "billy new",
  "new_password": "azeaze",
}


### load user data 
GET http://localhost:8000/login/loadUserData

### logout
POST http://localhost:8000/login/logout/0aa1967b91c4c1232cf87c8c6373a035d08255d2
Content-Type: application/json

