

### login an user
POST http://localhost:8000/login/loginUser
Content-Type: application/json

{
    "username": "admin2",
    "password": "aze"
}


### create a livreur
POST http://localhost:8000/login/create_livreur
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

{
    "username": "Neymar",
    "password": "aze"
}

###
GET http://localhost:8000/login/getAllUsers

###
GET http://localhost:8000/login/getAllLivreurs
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


###
GET http://localhost:8000/login/get_users_connected


### Créer un utilisateur avec la méthode POST
POST http://localhost:8000/login/create
Content-Type: application/json

{
  "username": "livreur random",
  "password": "aze",  
  "is_admin": false
}

### delete user
DELETE http://localhost:8000/login/delete_livreur/18
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

### get user
GET http://localhost:8000/login/get_user/18
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

###
DELETE http://localhost:8000/login/delete_user/18

###
PUT http://localhost:8000/login/update_user/18
Content-Type: application/json
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2


{
  "new_username": "billy new",
  "new_password": "azeaze",
}


### load user data 
GET http://localhost:8000/login/loadUserData

### logout
POST http://localhost:8000/login/logout/0aa1967b91c4c1232cf87c8c6373a035d08255d2
Content-Type: application/json

