
### assigner la tournee 2 a Ronaldo (id = 5)
POST http://localhost:8000/tournee/assigner_tournee/2
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2
Content-Type: application/json

{
    "livreur_id": 3
}

### get all tournee 
GET http://localhost:8000/tournee/get_all_tournee
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

###
GET http://localhost:8000/tournee/get_tournees_livreur
Authorization: Token 2d54b7411a461a4099d996bb90e02551038134f3

#47cf7bb92dbfa2649aa20fd3ff1fa82de9a94771


### renvoi les commandes d'une tournee specifique 
GET http://localhost:8000/tournee/get_commandes_from_tournee/2
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

//tournees/<int:id_tournee>/commandes/details

### renvoi la liste des caisses dans la commande de la tournee 1
GET http://localhost:8000/tournee/1/commandes/details
Authorization: Token 0aa1967b91c4c1232cf87c8c6373a035d08255d2

